version: '3.7'

services:
  application:
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=autoapp.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0"]