version: '3.7'

services:
  application:
    image: application
    build:
      context: .
      target: production
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV=production
  nginx:
    image: nginx
    build:
      context: nginx
    ports:
      - 80:80