version: '3.7'

services:
  application:
    build:
      target: production
    expose:
      - "5000"
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV=production
    env_file:
        - secrets.env
  nginx:
    image: nginx
    build:
      context: nginx
    ports:
      - 80:80