version: '3.7'

services:
  application:
    image: application
    build:
      context: .
      target: development
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      target: development
    command: ["celery", "-A", "application.celery_app:app", "worker", "--loglevel=info"]
    env_file:
      - secrets.env
  monitor:
    build:
      context: .
      target: development
    command: "flower -A application.celery_app:app --port=5555 --broker=redis://redis:6379/0"
    ports:
      - "5555:5555"
    env_file:
      - secrets.env