version: '3.7'

services:
  application:
    image: application
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=autoapp.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
  nginx:
    image: nginx
    build:
      context: nginx
    ports:
      - 80:80